version: 0.2

env:
  secrets-manager:
    AWS_S3_WEB_URL: $AWS_SECRET_ARN:AWS_S3_WEB_IDENTITY_URL
    AWS_WEB_CLOUDFRONT_DISTRIBUTION_ID: $AWS_SECRET_ARN:AWS_WEB_IDENTITY_CLOUDFRONT_DISTRIBUTION_ID

    VITE_AWS_S3_WEB_STORAGE_ASSETS_URL: $AWS_SECRET_ARN:AWS_S3_ASSET_URL
    VITE_COOKIE_DOMAIN: $AWS_SECRET_ARN:COOKIE_DOMAIN
    VITE_IDENTITY_WEB_URL: $AWS_SECRET_ARN:ENV_WEB_IDENTITY_URL
    VITE_API_URL: $AWS_SECRET_ARN:ENV_API_URL

phases:
  pre_build:
    commands:
      - npm install -g pnpm@9.4.0
      - pnpm install
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

      - echo VITE_WEB_URL=$VITE_IDENTITY_WEB_URL >> .env
      - echo VITE_API_URL=$VITE_API_URL >> .env
      - echo VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN >> .env

      - echo VITE_AWS_S3_WEB_STORAGE_ASSETS_URL=$VITE_AWS_S3_WEB_STORAGE_ASSETS_URL >> .env

      - pnpm build
      - aws configure list-profiles #addstte
      - aws s3 sync dist $AWS_S3_WEB_URL --delete
      - aws cloudfront create-invalidation --distribution-id $AWS_WEB_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
  post_build:
    commands:
      - echo $CODEBUILD_BUILD_SUCCEEDING
